### ISSUE TITLE
Missing build instruction for linux

### ISSUE THREAD

**Issue by freddii** [herace/AnimeEffects#19]
There is no build instruction for linux in the README.md file.

For debian i run:  

```
sudo apt-get install qtcreator -y  
git clone https://github.com/herace/AnimeEffects  
cd AnimeEffects  
qtcreator ./src/AnimeEffects.pro  
```
Now in qt-creator click on  configure project.  
Now press ctrl+b to build it.  

When building done run it with:  
./AnimeEffects/build-AnimeEffects-Desktop-Debug/AnimeEffects

**Comment by orophix** [comment]
qt creator is empty after following this

**Comment by freddii** [comment]
What operating system do you use?
What output do you get from:
`ls -l ./src/AnimeEffects.pro`

**Comment by orophix** [comment]
Ubuntu 20.04

```
ls -l ./src/AnimeEffects.pro
-rw-rw-r-- 1 orophix orophix 1818 Feb  5 04:29 ./src/AnimeEffects.pro

```
[Link to Screenshot](https://nyah.moe/img/RDk8q)

**Comment by freddii** [comment]
Are you able to open the file AnimeEffects.pro as a project inside qt-creator?

**Comment by orophix** [comment]
When I do that I get:

`No build found in /home/orophix/Tools/AnimeEffects/src matching project /home/orophix/Tools/AnimeEffects/src/AnimeEffects.pro.`

**Comment by orophix** [comment]
Still doesn't work

**Comment by orophix** [comment]
Should I create a new issue?
