### ISSUE TITLE
[BUG] Make AnimeEffects work with dark desktop theme

### ISSUE THREAD

**Issue by larpon** [herace/AnimeEffects#9]
I recently changed to a dark desktop theme and, while still usable, AnimeEffects has a few quirks in this direction:
![image](https://user-images.githubusercontent.com/768942/69494981-00516500-0ec2-11ea-8e26-cfb966b6760c.png)

**Comment by herace** [comment]
Oh wow, never knew AnimeEffects do something like that...this can put some people off. A sleek Dark-Theme for AnimeEffects will be excellent and draw more people in using this app. 

Honestly speaking im not sure how QT handles the UI theme based on the users current Desktop Environment  window scheme / color pallet. :disappointed:

**Comment by larpon** [comment]
Yeah. Rumour has it that QtWidgets is a bit broken in this area (QML should work better with system provided themes) and that we maybe need to build an explicit dark theme for users to switch to. I've been talking to @azagaya and @Jose-Moreno about it on Discord / IRC (you're welcome to pop by and say hello!)

**Comment by larpon** [comment]
Hmm.. It might be the hardcoded styles in [data/stylesheet](https://github.com/herace/AnimeEffects/tree/master/data/stylesheet) - it might be enough to simply remove any hardcoded colors?

**Comment by azagaya** [comment]
Hi! i think that actually we should add some hardcoded colors, to override what is set up by the system. I could try if you give me a list of the widgets that have this issue.. I see spinboxes are affected, aren't they?

**Comment by larpon** [comment]
We can get far by simply removing hard coded colors and do some tweaking in the code base:
![image](https://user-images.githubusercontent.com/768942/69544429-fdbd4100-0f8f-11ea-9db6-d6d139663442.png)
There's still quite a bit of hard coded colors in there.

As @azagaya and I has discussed - it's probably worth it to include theme support and include 3-4 styles:
* `System/Default` (Use system provided styles. Should work with both light & dark system themes as opposed to current mixture)
* `Classic/Original` (The current theme)
* `Light` (a more modern take on the classic)
* `Dark` (a modern dark theme)

**Comment by larpon** [comment]
... just suggestions - but I'd like to be able to at least use it with a dark system theme :)

**Comment by larpon** [comment]
I made a quick test branch here:
https://github.com/Larpon/AnimeEffects/tree/test/remove-all-hard-coded-colors

(Will need a dark system theme)

**Comment by larpon** [comment]
Fixed in #16
